// <auto-generated />
namespace IPAMS_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IPAMS_Admission_Crud_BE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IPAMS_Admission_Crud_BE));
        
        string IMigrationMetadata.Id
        {
            get { return "202105030716228_IPAMS_Admission_Crud_BE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
