// <auto-generated />
namespace IPAMS_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IPAMS_Admission_Crud_BE4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IPAMS_Admission_Crud_BE4));
        
        string IMigrationMetadata.Id
        {
            get { return "202106011019262_IPAMS_Admission_Crud_BE4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
